export const seedData = {
  users: [
    {
      id: 'user-admin',
      name: 'Aarav Mehta',
      email: 'admin@technova.com',
      password: 'demo123',
      role: 'Administrator',
    },
  ],
  sessions: [],
  profile: {
    companyName: 'TechNova Solutions Pvt Ltd',
    shortName: 'TN',
    location: 'Bengaluru, Karnataka',
    businessType: 'Private Limited Company',
    industry: 'Information Technology',
    companySize: '11 - 50 Employees (Small)',
    udyamRegistration: 'UDYAM-KR-00-1234567',
    verificationStatus: 'Verification Complete',
    employees: 32,
    foundedYear: '2018',
    pan: 'AAACT1234F',
    website: 'https://technova.example',
    description:
      'Product engineering and cloud automation company serving manufacturing and retail MSMEs.',
  },
  settings: {
    companyName: 'TechNova Solutions Pvt Ltd',
    businessEmail: 'admin@technova.com',
    phone: '+91 98765 43210',
    timezone: 'Asia/Kolkata (IST)',
    notifications: {
      email: true,
      sms: false,
      digest: true,
    },
    security: {
      twoFactor: false,
      sessionTimeout: '30 minutes',
    },
    backup: {
      frequency: 'Weekly',
      retention: '90 days',
    },
    language: 'English',
  },
  compliances: [
    {
      id: 'cmp-gstr1',
      title: 'GST Filing (GSTR-1)',
      desc: 'Monthly return for outward supplies.',
      date: '2026-03-15',
      status: 'PENDING',
      actionLabel: 'Open filing guide',
      route: '/guidance',
    },
    {
      id: 'cmp-epf',
      title: 'EPF Contribution',
      desc: 'Employees Provident Fund monthly deposit.',
      date: '2026-03-11',
      status: 'COMPLETED',
      actionLabel: 'View record',
      route: '/alerts',
    },
    {
      id: 'cmp-tds',
      title: 'TDS Payment',
      desc: 'Tax deducted at source for professional fees.',
      date: '2026-03-18',
      status: 'PENDING',
      actionLabel: 'Review payment',
      route: '/alerts',
    },
    {
      id: 'cmp-ptax',
      title: 'Professional Tax Payment',
      desc: 'State-level professional tax payment for Karnataka operations.',
      date: '2026-03-08',
      status: 'OVERDUE',
      actionLabel: 'Pay now',
      route: '/alerts',
    },
  ],
  alerts: [
    {
      id: 'alert-ptax',
      type: 'overdue',
      title: 'Professional Tax Payment Overdue',
      desc: 'The professional tax payment due on 2026-03-08 is overdue and late fees may apply.',
      date: '2026-03-08',
      action: 'Pay Now',
      status: 'OPEN',
      relatedComplianceId: 'cmp-ptax',
    },
    {
      id: 'alert-gstr1',
      type: 'warning',
      title: 'GST Filing (GSTR-1) Due Soon',
      desc: 'The March GSTR-1 return is due on 2026-03-15. Draft and supporting documents are ready for review.',
      date: '2026-03-15',
      action: 'Review Draft',
      status: 'OPEN',
      relatedComplianceId: 'cmp-gstr1',
    },
    {
      id: 'alert-guidance',
      type: 'info',
      title: 'Updated Data Privacy Guidance Available',
      desc: 'A new checklist covering vendor data processing and retention controls is available.',
      date: '2026-03-12',
      action: 'Read More',
      status: 'OPEN',
      relatedComplianceId: null,
    },
  ],
  guidance: {
    topic: 'GSTR-1 Filing',
    description:
      'Follow the guided checklist to prepare, validate, and submit your monthly outward supplies return.',
    portalUrl: 'https://www.gst.gov.in/',
    steps: [
      {
        id: 'step-1',
        num: 1,
        title: 'Gather sales records',
        desc: 'Collect invoices, debit notes, and export records for the filing period.',
        docs: ['Sales Register', 'Export Invoices'],
      },
      {
        id: 'step-2',
        num: 2,
        title: 'Validate GSTINs',
        desc: 'Review customer GSTIN values and ensure invoice numbers match your books.',
        docs: ['Customer Master', 'Invoice Summary'],
      },
      {
        id: 'step-3',
        num: 3,
        title: 'Prepare portal upload',
        desc: 'Map data to the portal template and verify taxable values before upload.',
        docs: ['Portal Template', 'Tax Summary'],
      },
      {
        id: 'step-4',
        num: 4,
        title: 'Submit and archive',
        desc: 'File the return on the portal and keep the acknowledgement in your document vault.',
        docs: ['Acknowledgement Copy'],
      },
    ],
    requiredDocs: [
      { id: 'doc-sales-register', name: 'Sales Register', status: 'ready' },
      { id: 'doc-bank-statement', name: 'Bank Statement', status: 'ready' },
      { id: 'doc-export-records', name: 'Export Records', status: 'pending' },
      { id: 'doc-previous-return', name: 'Previous Return', status: 'ready' },
    ],
  },
  schemes: [
    {
      id: 'scheme-cgs',
      title: 'Credit Guarantee Scheme (CGS)',
      ministry: 'MSME Ministry',
      match: 96,
      tags: ['FINANCING', 'MANUFACTURING'],
      eligibility: 'Registered MSMEs with working-capital or expansion requirements.',
      benefits: 'Collateral-free credit support up to Rs 5 crore through participating lenders.',
      status: 'RECOMMENDED',
    },
    {
      id: 'scheme-digital',
      title: 'Digital MSME Scheme',
      ministry: 'Ministry of Electronics and IT',
      match: 91,
      tags: ['TECHNOLOGY', 'DIGITIZATION'],
      eligibility: 'MSMEs adopting cloud, ERP, cybersecurity, or automation platforms.',
      benefits: 'Support for digital transformation, software onboarding, and process automation.',
      status: 'RECOMMENDED',
    },
    {
      id: 'scheme-zed',
      title: 'ZED Certification Scheme',
      ministry: 'QCI and Ministry of MSME',
      match: 77,
      tags: ['QUALITY', 'SUSTAINABILITY'],
      eligibility: 'MSMEs with valid Udyam registration seeking certification or process maturity.',
      benefits: 'Financial assistance for assessment, certification, and quality improvements.',
      status: 'RECOMMENDED',
    },
  ],
  loans: [
    {
      id: 'loan-hdfc-growth',
      bank: 'HDFC Bank',
      type: 'MSME Growth Loan',
      interest: '8.45% - 10.50%',
      minRate: 8.45,
      amount: 'Rs 10L - Rs 50L',
      maxAmountLakhs: 50,
      tenure: 'Up to 5 years',
      purpose: 'Working Capital',
      features: ['No collateral up to Rs 25L', 'Fast processing', 'Digital application'],
      logoText: 'HB',
      status: 'RECOMMENDED',
    },
    {
      id: 'loan-sidbi-speed',
      bank: 'SIDBI',
      type: 'SPEED Plus',
      interest: '6.75% onwards',
      minRate: 6.75,
      amount: 'Rs 25L - Rs 2Cr',
      maxAmountLakhs: 200,
      tenure: 'Up to 3 years',
      purpose: 'Machinery Purchase',
      features: ['Low interest for tech units', 'Minimal paperwork', 'Direct loan support'],
      logoText: 'SI',
      status: 'RECOMMENDED',
    },
    {
      id: 'loan-sbi-term',
      bank: 'State Bank of India',
      type: 'SME Smart Score Loan',
      interest: '7.90% onwards',
      minRate: 7.9,
      amount: 'Rs 50L - Rs 3Cr',
      maxAmountLakhs: 300,
      tenure: 'Up to 7 years',
      purpose: 'Expansion Capital',
      features: ['Higher sanction limit', 'Branch support', 'Term and cash-credit options'],
      logoText: 'SB',
      status: 'RECOMMENDED',
    },
  ],
  documents: [],
  assistantHistory: [
    {
      id: 'assistant-seed',
      role: 'assistant',
      text: 'Hello. Ask about filings, schemes, loans, or documents and I will respond with data from your workspace.',
      timestamp: '2026-03-12T09:00:00.000Z',
    },
  ],
  storageLimitBytes: 10737418240,
};
